[package]
name = "heirloom-keeper"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
anchor-lang = "1.1.2"
anyhow = "1"
bincode = "1"
clap = { version = "4", features = ["derive", "env"] }
heirloom = { path = "../programs/heirloom", features = ["no-entrypoint"] }
heirloom-client = { version = "0.1.0", path = "../client" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
solana-account-decoder-client-types = "3.1.14"
solana-client = "3"
solana-commitment-config = "3.1.1"
solana-sdk = "3"
solana-system-interface = { version = "2", features = ["bincode"] }
# TODO: add solana-client, tokio, anyhow, tracing when logic lands
