skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
heirloom = "Egn9Kgqa8sLT2F5u5DS26Bg791eW51HfKKuqSSp8euke"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
